version: '3.1'

services:
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: john
  #     POSTGRES_PASSWORD: mysecretpassword
  #   expose:
  #     - 5432

  delete_write_app:
    build: delete_write_apis/
    image: delete_write_img
    command: flask --app src run -p 8080
    environment:
      APP_DB_HOST: db
      APP_DB_USER: john
      APP_DB_PASSWORD: mysecretpassword
    expose:
      - 8080
    # depends_on:
    #   - db


# -wait tcp://db:5432 -wait tcp://myapp:8000 -timeout 10s
  delete_write_apis-tests:
    image: delete_write_img
    command: dockerize
        -wait tcp://delete_write_app:8000 -timeout 10s
        bash -c "node db/init.js && yarn test"
    environment:
      APP_URL: http://myapp:8000
      APP_DB_HOST: db
      APP_DB_USER: john
      APP_DB_PASSWORD: mysecretpassword
    # depends_on:
    #   - db
    #   - myapp

# run with: docker-compose up --build --abort-on-container-exit